/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DetailedInfo;
import java.io.*;
import javax.swing.JFrame;
import Koneksi.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
import com.formdev.flatlaf.*;// Import Cupertino LAF
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author hamud
 */
public class BarangDetailed extends javax.swing.JFrame {

    /**
     * Creates new form BarangDetailed
     */
    private Connection conn;
    private int barangId;
    private int idPengirim;
    private int idKategori;
    public BarangDetailed() {
        conn=Koneksi.getConnection();
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btn_barang_ubah.setEnabled(false);
        t_alamat_penerima.setEnabled(false);
        t_alamat_pengirim.setEnabled(false);
        t_desc_barang.setEnabled(false);
        t_namaPenerima.setEnabled(false);
        t_namaPengirim.setEnabled(false);
        t_nama_barang.setEnabled(false);
        t_notelp_penerima.setEnabled(false);
        t_notelp_pengirim.setEnabled(false);
        dd_kategori_barang.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_barangID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_namaPengirim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_namaPenerima = new javax.swing.JTextField();
        t_alamat_pengirim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_alamat_penerima = new javax.swing.JTextField();
        t_notelp_pengirim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_notelp_penerima = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t_nama_barang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_desc_barang = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btn_hapus_barang = new javax.swing.JButton();
        btn_barang_ubah = new javax.swing.JButton();
        btn_c1_kembali = new javax.swing.JButton();
        dd_kategori_barang = new javax.swing.JComboBox<>();
        btn_mode_ubah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_barangID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_barangID.setText("Barang ID:0");

        jLabel7.setText("Nama");

        jLabel8.setText("Nama Penerima");

        t_alamat_pengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_alamat_pengirimActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat");

        jLabel10.setText("Alamat Penerima");

        jLabel11.setText("No Telepon");

        jLabel12.setText("No Telepon Penerima");

        jLabel13.setText("Barang");

        t_nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nama_barangActionPerformed(evt);
            }
        });

        jLabel14.setText("Deskripsi Barang");

        t_desc_barang.setColumns(20);
        t_desc_barang.setRows(5);
        jScrollPane4.setViewportView(t_desc_barang);

        jLabel15.setText("Kategori");

        btn_hapus_barang.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btn_hapus_barang.setText("Hapus");
        btn_hapus_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapus_barangMouseClicked(evt);
            }
        });
        btn_hapus_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_barangActionPerformed(evt);
            }
        });

        btn_barang_ubah.setBackground(new java.awt.Color(102, 102, 255));
        btn_barang_ubah.setText("Ubah");
        btn_barang_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_barang_ubahActionPerformed(evt);
            }
        });

        btn_c1_kembali.setText("Kembali");
        btn_c1_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_c1_kembaliMouseClicked(evt);
            }
        });
        btn_c1_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1_kembaliActionPerformed(evt);
            }
        });

        btn_mode_ubah.setBackground(new java.awt.Color(102, 102, 255));
        btn_mode_ubah.setText("Mode Ubah");
        btn_mode_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mode_ubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dd_kategori_barang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_nama_barang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(t_namaPengirim)
                                    .addComponent(t_notelp_pengirim)
                                    .addComponent(t_alamat_pengirim)
                                    .addComponent(label_barangID, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_namaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(t_alamat_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(t_notelp_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(btn_c1_kembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_mode_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_barang_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_hapus_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_barangID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_c1_kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_namaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_namaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_alamat_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_alamat_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_notelp_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_notelp_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dd_kategori_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapus_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_barang_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mode_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t_alamat_pengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_alamat_pengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_alamat_pengirimActionPerformed

    private void t_nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nama_barangActionPerformed

    private void btn_hapus_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapus_barangMouseClicked

    }//GEN-LAST:event_btn_hapus_barangMouseClicked
    private int SearchTransaksiByIdClient(int id){
        String query = "SELECT id from transaksi where fk_barang = ? ";
        try {
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, this.barangId);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                return rs.getInt("id");
            }
            ps.close();
            rs.close();
        } catch (Exception e) {
        }
        return 0;
    }
    private void hapusTransaksi(int barangId){
        String deleteTransaksiSQL = "DELETE FROM transaksi WHERE fk_barang = ?";
        try (PreparedStatement ps = conn.prepareStatement(deleteTransaksiSQL)) {
            ps.setInt(1, barangId); // Set the barang ID to delete

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data transaksi berhasil dihapus");
            } else {
                JOptionPane.showMessageDialog(this, "Data transaksi tidak ditemukan atau gagal dihapus");
            }
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    private void hapusBarang(int idBarang){
        String deleteBarangSQL = "DELETE FROM barang WHERE id = ?";
        try (PreparedStatement ps = conn.prepareStatement(deleteBarangSQL)) {
            ps.setInt(1, idBarang); // ID barang to delete

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data barang berhasil dihapus");
                // Refresh the table or list
            } else {
                JOptionPane.showMessageDialog(this, "Data barang tidak ditemukan atau gagal dihapus");
            }
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    private void btn_hapus_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_barangActionPerformed
        int response  = JOptionPane.showConfirmDialog(this, "Seriusan mau update?", "Update Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            int id = SearchTransaksiByIdClient(this.barangId);
            if(id!=0){
                hapusTransaksi(barangId);
                hapusBarang(barangId);
                this.dispose();
            }
        }

    }//GEN-LAST:event_btn_hapus_barangActionPerformed
    private int updatePengirim(int idPengirim,String nama, String alamat,String noTelp){
         String sql = "UPDATE client SET nama = ?, alamat = ?, no_telp = ? WHERE id = ?";
    
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setString(2, alamat);
            ps.setString(3, noTelp);
            ps.setInt(4, idPengirim); // Ensure you have the client's ID for the WHERE clause

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                
                return 1;
                
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau gagal diperbarui");
            }
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
        }
        return 0 ;
    }
    private int searchKategoriId(String name) {
        String query = "SELECT id FROM kategori WHERE nama = ?";
        try {
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, name);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                return rs.getInt("id");
            }
            rs.close();
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null,e);
        }
         return 0;   
    }
    private void updateBarang(int idBarang, String nama, int fk_kat, int fk_c, String desc, String nama_penerima, String alamat_penerima, String notelp_penerima) {
        String updateBarangSQL = "UPDATE barang SET nama = ?, fk_kategori = ?, fk_client = ?, description = ?, nama_penerima = ?, alamat_penerima = ?, notelp_penerima = ? WHERE id = ?";
        try (PreparedStatement ps = conn.prepareStatement(updateBarangSQL)) {
            ps.setString(1, nama);
            ps.setInt(2, fk_kat); // ID kategori
            ps.setInt(3, fk_c);   // ID client
            ps.setString(4, desc);
            ps.setString(5, nama_penerima);
            ps.setString(6, alamat_penerima);
            ps.setString(7, notelp_penerima);
            ps.setInt(8, idBarang); // ID barang to update

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data barang berhasil diperbarui");
                
            } else {
                JOptionPane.showMessageDialog(this, "Data barang tidak ditemukan atau gagal diperbarui");
            }
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void btn_barang_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_barang_ubahActionPerformed
        int response  = JOptionPane.showConfirmDialog(this, "Seriusan mau update?", "Update Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            //Pengirim
            int idPengirim=this.idPengirim;
            String namaPengirim = t_namaPengirim.getText();
            String alamat = t_alamat_pengirim.getText();
            String noTelpPengirim = t_notelp_pengirim.getText();
            //Barang
            int idBarang = this.barangId;
            String namaPenerima = t_namaPenerima.getText();
            String alamatPenerima = t_alamat_penerima.getText();
            String noTelpPenerima = t_alamat_penerima.getText();
            String namaBarang= t_nama_barang.getText();
            String descBarang = t_desc_barang.getText();
            //Kategori
            
            String namaKategori = dd_kategori_barang.getSelectedItem().toString();
            
            // Input client
            int idClient = updatePengirim(idPengirim,namaPengirim, alamat, noTelpPengirim);
            if (idClient == 0) {
                JOptionPane.showMessageDialog(this, "Gagal update data client!");
                return;
            }
            // Cari ID kategori
            int idKategori = searchKategoriId(namaKategori);
            if (idKategori == 0) {
                JOptionPane.showMessageDialog(this, "Kategori tidak ditemukan!");
                return;
            }
            
            // Update Barang
            //int idBarang, String nama, int fk_kat, int fk_c, String desc, String nama_penerima, String alamat_penerima, String notelp_penerima
            updateBarang(idBarang, namaBarang, idKategori, idPengirim, descBarang, namaPenerima, alamatPenerima, noTelpPenerima);
        }
        
    }//GEN-LAST:event_btn_barang_ubahActionPerformed

    private void btn_c1_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c1_kembaliMouseClicked

    }//GEN-LAST:event_btn_c1_kembaliMouseClicked

    private void btn_c1_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1_kembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_c1_kembaliActionPerformed
    private void rubahModeEdit(){
        if(btn_barang_ubah.isEnabled()==true){
            btn_barang_ubah.setEnabled(false);
            t_alamat_penerima.setEnabled(false);
            t_alamat_pengirim.setEnabled(false);
            t_desc_barang.setEnabled(false);
            t_namaPenerima.setEnabled(false);
            t_namaPengirim.setEnabled(false);
            t_nama_barang.setEnabled(false);
            t_notelp_penerima.setEnabled(false);
            t_notelp_pengirim.setEnabled(false);
            dd_kategori_barang.setEnabled(false);
        }else{
            btn_barang_ubah.setEnabled(true);
            t_alamat_penerima.setEnabled(true);
            t_alamat_pengirim.setEnabled(true);
            t_desc_barang.setEnabled(true);
            t_namaPenerima.setEnabled(true);
            t_namaPengirim.setEnabled(true);
            t_nama_barang.setEnabled(true);
            t_notelp_penerima.setEnabled(true);
            t_notelp_pengirim.setEnabled(true);
            dd_kategori_barang.setEnabled(true);
        }
    }
    private void btn_mode_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mode_ubahActionPerformed
        rubahModeEdit();
    }//GEN-LAST:event_btn_mode_ubahActionPerformed
    private void loadCategories() {
        dd_kategori_barang.removeAllItems();
        try {
            String query = "SELECT nama FROM kategori";
            PreparedStatement st = conn.prepareStatement(query);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                dd_kategori_barang.addItem(rs.getString("nama"));
            }
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading categories: " + e.getMessage());
        }
    }
    public void setBarangDetails(int idPengirim,int idBarang, int idKategori, String namaPengirim, String alamatPengirim, String noTelpPengirim,
                                  String namaPenerima, String alamatPenerima, String noTelpPenerima,
                                  String namaBarang, String desc, String kategori) {
        this.idPengirim=idPengirim;
        t_namaPengirim.setText(namaPengirim);
        t_namaPenerima.setText(namaPenerima);
        t_alamat_pengirim.setText(alamatPengirim);
        t_notelp_pengirim.setText(noTelpPengirim);
        this.barangId = idBarang;
        this.idKategori = idKategori;
        this.setTitle("Barangv"+barangId);
        label_barangID.setText("Barang ID: "+idBarang);
        t_alamat_penerima.setText(alamatPenerima);
        t_notelp_penerima.setText(noTelpPenerima);
        t_nama_barang.setText(namaBarang);
        t_desc_barang.setText(desc);
        
        
        // Load categories into combo box
        loadCategories();
        dd_kategori_barang.setSelectedItem(kategori);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set FlatLaf Light look and feel
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangDetailed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_barang_ubah;
    private javax.swing.JButton btn_c1_kembali;
    private javax.swing.JButton btn_hapus_barang;
    private javax.swing.JButton btn_mode_ubah;
    private javax.swing.JComboBox<String> dd_kategori_barang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_barangID;
    private javax.swing.JTextField t_alamat_penerima;
    private javax.swing.JTextField t_alamat_pengirim;
    private javax.swing.JTextArea t_desc_barang;
    private javax.swing.JTextField t_namaPenerima;
    private javax.swing.JTextField t_namaPengirim;
    private javax.swing.JTextField t_nama_barang;
    private javax.swing.JTextField t_notelp_penerima;
    private javax.swing.JTextField t_notelp_pengirim;
    // End of variables declaration//GEN-END:variables
}
