/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DetailedInfo;
import java.io.*;
import javax.swing.JFrame;
import Koneksi.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Koneksi.Koneksi;
import com.formdev.flatlaf.*;// Import Cupertino LAF
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



import javax.swing.*;

/**
 *
 * @author hamud
 */
public class TransaksiDetailed extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiDetailed
     */
    private int id;
    private int ClientId;
    private int barangId;
    private Connection conn;
    public TransaksiDetailed() {
        initComponents();
        conn= Koneksi.getConnection();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btn_transaksi_ubah.setEnabled(false);
        t_namaBarang.setEnabled(false);
        t_namaPengirim.setEnabled(false);
        t_pengirimTelp.setEnabled(false);
        t_status.setEnabled(false);
        t_tanggal.setEnabled(false);
        t_tujuanBarang.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_transaksiId = new javax.swing.JLabel();
        btn_c1_kembali = new javax.swing.JButton();
        t_namaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_namaPengirim = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_pengirimTelp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        btn_transaksi_ubah = new javax.swing.JButton();
        btn_input_barang = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        t_tujuanBarang = new javax.swing.JTextField();
        btn_mode_ubah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label_transaksiId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_transaksiId.setText("Transaksi ID:0");

        btn_c1_kembali.setText("Kembali");
        btn_c1_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_c1_kembaliMouseClicked(evt);
            }
        });
        btn_c1_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1_kembaliActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Barang");

        jLabel8.setText("Nama Pengirim");

        jLabel9.setText("Telepon Pengirim");

        t_pengirimTelp.setPreferredSize(new java.awt.Dimension(64, 32));

        jLabel10.setText("Status");

        jLabel11.setText("Tanggal");

        btn_transaksi_ubah.setBackground(new java.awt.Color(102, 102, 255));
        btn_transaksi_ubah.setText("Ubah");
        btn_transaksi_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksi_ubahActionPerformed(evt);
            }
        });

        btn_input_barang.setBackground(new java.awt.Color(0, 204, 0));
        btn_input_barang.setText("Tandai Keluar");
        btn_input_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_input_barangMouseClicked(evt);
            }
        });
        btn_input_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_input_barangActionPerformed(evt);
            }
        });

        jLabel12.setText("Tujuan Barang");

        btn_mode_ubah.setBackground(new java.awt.Color(102, 102, 255));
        btn_mode_ubah.setText("Mode Ubah");
        btn_mode_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mode_ubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mode_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_transaksi_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_input_barang))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_transaksiId, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(btn_c1_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_namaBarang)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_namaPengirim)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_status)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_pengirimTelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_tujuanBarang)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_tanggal)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_transaksiId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_c1_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_namaPengirim))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_pengirimTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tujuanBarang)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tanggal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_input_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_transaksi_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mode_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_c1_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c1_kembaliMouseClicked

    }//GEN-LAST:event_btn_c1_kembaliMouseClicked

    private void btn_c1_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1_kembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_c1_kembaliActionPerformed

    private void btn_input_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_input_barangMouseClicked

    }//GEN-LAST:event_btn_input_barangMouseClicked

    private void btn_input_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_input_barangActionPerformed
        int response  = JOptionPane.showConfirmDialog(this, "Yakin untuk update?", "Update Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(response==JOptionPane.YES_OPTION){
            String sql = "Update transaksi SET status =? where id=?";
            try {
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, "keluar");
                st.setInt(2, id);

                int rowsAffected = st.executeUpdate();

                if(rowsAffected>0){
                   JOptionPane.showMessageDialog(this, "Status updated successfully.");
                   t_status.setText("keluar");
                   t_status.setBackground(Color.RED);

                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update status.");

                }

            } catch (Exception e) {
                Logger.getLogger(TransaksiDetailed.class.getName()).log(Level.SEVERE, null,e);
            }
        }
        
    }//GEN-LAST:event_btn_input_barangActionPerformed
    private void updatePengirim(int idPengirim,String nama, String noTelp){
         String sql = "UPDATE client SET nama = ?, no_telp = ? WHERE id = ?";
    
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            
            ps.setString(2, noTelp);
            ps.setInt(3, idPengirim); // Ensure you have the client's ID for the WHERE clause

            int rowsAffected = ps.executeUpdate();

            
            if (rowsAffected > 0) {
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau gagal diperbarui");
            }
        } catch (Exception e) {
            Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }
    private void updateTransaksi(String tanggal, String status, int id){
        String updateTransaksiSQL = "UPDATE transaksi SET tanggal = ?, status = ? WHERE id = ?";
        try {
            PreparedStatement ps = conn.prepareStatement(updateTransaksiSQL);
            
            java.sql.Date parsedDate = null;
            try {
                parsedDate = java.sql.Date.valueOf(tanggal);  // Converts String to java.sql.Date
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Format tanggal tidak valid", "Validasi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            ps.setDate(1, parsedDate);
            ps.setString(2, status);
            ps.setInt(3, id);
            int rowUpdated = ps.executeUpdate();
            
            if(rowUpdated>0){
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diperbarui", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }
    private void updateBarang(int idBarang, String nama, String alamat_penerima) {
    // SQL query to update only the barang's name and the penerima's address
    String updateBarangSQL = "UPDATE barang SET nama = ?, alamat_penerima = ? WHERE id = ?";
    try (PreparedStatement ps = conn.prepareStatement(updateBarangSQL)) {
        ps.setString(1, nama);            // Set the new barang's name
        ps.setString(2, alamat_penerima); // Set the new penerima's address
        ps.setInt(3, idBarang);           // Set the ID of the barang to update

        int rowsAffected = ps.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Data barang berhasil diperbarui");
        } else {
            JOptionPane.showMessageDialog(this, "Data barang tidak ditemukan atau gagal diperbarui");
        }
    } catch (Exception e) {
        Logger.getLogger(BarangDetailed.class.getName()).log(Level.SEVERE, null, e);
    }
}

    private void btn_transaksi_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksi_ubahActionPerformed
        int idT = this.id;
        int idB= this.barangId;
        int idC= this.ClientId;
        String namaBarang=t_namaBarang.getText();
        String namaPengirim = t_namaPengirim.getText();
        String noTelpPengirim = t_pengirimTelp.getText();
        String alamatTujuan = t_tujuanBarang.getText();
        String status = t_status.getText();
        String tanggal = t_tanggal.getText();
        
        updatePengirim(idC, namaPengirim,noTelpPengirim);
        updateTransaksi(tanggal, status, id);
        updateBarang(barangId, namaBarang,alamatTujuan);
        
        
    }//GEN-LAST:event_btn_transaksi_ubahActionPerformed
    private void rubahModeUbah(){
        if(btn_transaksi_ubah.isEnabled()==true){
            btn_transaksi_ubah.setEnabled(false);
            t_namaBarang.setEnabled(false);
            t_namaPengirim.setEnabled(false);
            t_pengirimTelp.setEnabled(false);
            t_status.setEnabled(false);
            t_tanggal.setEnabled(false);
            t_tujuanBarang.setEnabled(false);
        }else{
            btn_transaksi_ubah.setEnabled(true);
            t_namaBarang.setEnabled(true);
            t_namaPengirim.setEnabled(true);
            t_pengirimTelp.setEnabled(true);
            t_status.setEnabled(true);
            t_tanggal.setEnabled(true);
            t_tujuanBarang.setEnabled(true);
        }
    }
    private void btn_mode_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mode_ubahActionPerformed
        rubahModeUbah();
    }//GEN-LAST:event_btn_mode_ubahActionPerformed
    
    public void setTransaksiDetails(int clientid, int barangId, int transaksiId, String namaBarang,String namaPengirim, String pengirimTelp, String status, String tanggal, String tujuanBarang)
    {   
        id = transaksiId;
        this.barangId=barangId;
        this.ClientId=clientid;
        label_transaksiId.setText("Transaksi ID: "+ transaksiId);
        this.setTitle("Transaksi "+transaksiId);
        t_namaBarang.setText(namaBarang);
        t_namaPengirim.setText(namaPengirim);
        t_pengirimTelp.setText(pengirimTelp);
        t_status.setText(status);
        t_tanggal.setText(tanggal);
        t_tujuanBarang.setText(tujuanBarang);
        if(status.equals("masuk")){
            t_status.setBackground(Color.GREEN);
        }else{
            t_status.setBackground(Color.RED);
        }
        if(t_status.getText().equals("keluar")){
            btn_input_barang.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiDetailed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiDetailed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c1_kembali;
    private javax.swing.JButton btn_input_barang;
    private javax.swing.JButton btn_mode_ubah;
    private javax.swing.JButton btn_transaksi_ubah;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_transaksiId;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_namaPengirim;
    private javax.swing.JTextField t_pengirimTelp;
    private javax.swing.JTextField t_status;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JTextField t_tujuanBarang;
    // End of variables declaration//GEN-END:variables
}
